### ISSUE TITLE
JSONDecodeError: Extra data

### ISSUE THREAD

**Issue by werid** [sdushantha/vsco-dl#1]
Hi, 

did vsco website change something? I can no longer get this script to work, I just get the following error, no matter which user or how many pages:

>% vsco-dl.py ellingsenheidi 1
[+] Fetched data
Traceback (most recent call last):
  File "/home/weird/bin/vsco-dl.py", line 66, in <module>
    main()
  File "/home/weird/bin/vsco-dl.py", line 64, in main
    download(username=args.username, html=html)
  File "/home/weird/bin/vsco-dl.py", line 16, in download
    array = json.loads(data).get("medias").get("byId")
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 144758 (char 144757)

**Comment by sdushantha** [comment]
Hey sorry for the really late reply. I just saw this now.
Not sure why it is not working for you because everything seems to work on my computer.
